export default {
  artists: [
    {
      name: 'Bon Iver',
      image: 'https://i.scdn.co/image/d5ea2b221938b03e2096ef2c2caf2a0558014c1e',
      link: 'https://open.spotify.com/artist/4LEiUm1SRbFMgfqnQTwUbQ',
      genres: ['eau claire indie', 'melancholia', 'slowcore'],
    },
    {
      name: 'Mac DeMarco',
      image: 'https://i.scdn.co/image/e3d3e28c604a1c86e796e0d2aa7d4dc249f62e6f',
      link: 'https://open.spotify.com/artist/3Sz7ZnJQBIHsXLUSo0OQtM',
      genres: ['edmonton indie'],
    },
    {
      name: 'Bombay Bicycle Club',
      image: 'https://i.scdn.co/image/4a1e106fead0523ef38b09ebc5f83688e7bf7129',
      link: 'https://open.spotify.com/artist/3pTE9iaJTkWns3mxpNQlJV',
      genres: [
        'alternative dance',
        'british indie rock',
        'indie pop',
        'indie rock',
        'indietronica',
        'modern alternative rock',
        'modern rock',
        'new rave',
        'rock',
      ],
    },
    {
      name: 'Pompeya',
      image: 'https://i.scdn.co/image/36579841d646bd87bf12eee2c9da60430a2e1097',
      link: 'https://open.spotify.com/artist/6ECT62UWPniLG7KmWdwk37',
      genres: ['russian synthpop'],
    },

    {
      name: 'Bon Iver',
      image: 'https://i.scdn.co/image/d5ea2b221938b03e2096ef2c2caf2a0558014c1e',
      link: 'https://open.spotify.com/artist/4LEiUm1SRbFMgfqnQTwUbQ',
      genres: ['eau claire indie', 'melancholia', 'slowcore'],
    },
    {
      name: 'Mac DeMarco',
      image: 'https://i.scdn.co/image/e3d3e28c604a1c86e796e0d2aa7d4dc249f62e6f',
      link: 'https://open.spotify.com/artist/3Sz7ZnJQBIHsXLUSo0OQtM',
      genres: ['edmonton indie'],
    },
    {
      name: 'Bombay Bicycle Club',
      image: 'https://i.scdn.co/image/4a1e106fead0523ef38b09ebc5f83688e7bf7129',
      link: 'https://open.spotify.com/artist/3pTE9iaJTkWns3mxpNQlJV',
      genres: [
        'alternative dance',
        'british indie rock',
        'indie pop',
        'indie rock',
        'indietronica',
        'modern alternative rock',
        'modern rock',
        'new rave',
        'rock',
      ],
    },
    {
      name: 'Pompeya',
      image: 'https://i.scdn.co/image/36579841d646bd87bf12eee2c9da60430a2e1097',
      link: 'https://open.spotify.com/artist/6ECT62UWPniLG7KmWdwk37',
      genres: ['russian synthpop'],
    },

    {
      name: 'Bon Iver',
      image: 'https://i.scdn.co/image/d5ea2b221938b03e2096ef2c2caf2a0558014c1e',
      link: 'https://open.spotify.com/artist/4LEiUm1SRbFMgfqnQTwUbQ',
      genres: ['eau claire indie', 'melancholia', 'slowcore'],
    },
    {
      name: 'Mac DeMarco',
      image: 'https://i.scdn.co/image/e3d3e28c604a1c86e796e0d2aa7d4dc249f62e6f',
      link: 'https://open.spotify.com/artist/3Sz7ZnJQBIHsXLUSo0OQtM',
      genres: ['edmonton indie'],
    },
    {
      name: 'Bombay Bicycle Club',
      image: 'https://i.scdn.co/image/4a1e106fead0523ef38b09ebc5f83688e7bf7129',
      link: 'https://open.spotify.com/artist/3pTE9iaJTkWns3mxpNQlJV',
      genres: [
        'alternative dance',
        'british indie rock',
        'indie pop',
        'indie rock',
        'indietronica',
        'modern alternative rock',
        'modern rock',
        'new rave',
        'rock',
      ],
    },
    {
      name: 'Pompeya',
      image: 'https://i.scdn.co/image/36579841d646bd87bf12eee2c9da60430a2e1097',
      link: 'https://open.spotify.com/artist/6ECT62UWPniLG7KmWdwk37',
      genres: ['russian synthpop'],
    },
    {
      name: 'Bon Iver',
      image: 'https://i.scdn.co/image/d5ea2b221938b03e2096ef2c2caf2a0558014c1e',
      link: 'https://open.spotify.com/artist/4LEiUm1SRbFMgfqnQTwUbQ',
      genres: ['eau claire indie', 'melancholia', 'slowcore'],
    },
    {
      name: 'Mac DeMarco',
      image: 'https://i.scdn.co/image/e3d3e28c604a1c86e796e0d2aa7d4dc249f62e6f',
      link: 'https://open.spotify.com/artist/3Sz7ZnJQBIHsXLUSo0OQtM',
      genres: ['edmonton indie'],
    },
    {
      name: 'Bombay Bicycle Club',
      image: 'https://i.scdn.co/image/4a1e106fead0523ef38b09ebc5f83688e7bf7129',
      link: 'https://open.spotify.com/artist/3pTE9iaJTkWns3mxpNQlJV',
      genres: [
        'alternative dance',
        'british indie rock',
        'indie pop',
        'indie rock',
        'indietronica',
        'modern alternative rock',
        'modern rock',
        'new rave',
        'rock',
      ],
    },
    {
      name: 'Pompeya',
      image: 'https://i.scdn.co/image/36579841d646bd87bf12eee2c9da60430a2e1097',
      link: 'https://open.spotify.com/artist/6ECT62UWPniLG7KmWdwk37',
      genres: ['russian synthpop'],
    },
  ],
};
