export default {
  artists: [
    {
      name: 'Bon Iver',
      image: 'https://i.scdn.co/image/d5ea2b221938b03e2096ef2c2caf2a0558014c1e',
      link: 'https://open.spotify.com/artist/4LEiUm1SRbFMgfqnQTwUbQ',
      genres: ['eau claire indie', 'melancholia', 'slowcore'],
    },
    {
      name: 'Mac DeMarco',
      image: 'https://i.scdn.co/image/e3d3e28c604a1c86e796e0d2aa7d4dc249f62e6f',
      link: 'https://open.spotify.com/artist/3Sz7ZnJQBIHsXLUSo0OQtM',
      genres: ['edmonton indie'],
    },
    {
      name: 'Bombay Bicycle Club',
      image: 'https://i.scdn.co/image/4a1e106fead0523ef38b09ebc5f83688e7bf7129',
      link: 'https://open.spotify.com/artist/3pTE9iaJTkWns3mxpNQlJV',
      genres: [
        'alternative dance',
        'british indie rock',
        'indie pop',
        'indie rock',
        'indietronica',
        'modern alternative rock',
        'modern rock',
        'new rave',
        'rock',
      ],
    },
    {
      name: 'Pompeya',
      image: 'https://i.scdn.co/image/36579841d646bd87bf12eee2c9da60430a2e1097',
      link: 'https://open.spotify.com/artist/6ECT62UWPniLG7KmWdwk37',
      genres: ['russian synthpop'],
    },

    {
      name: 'Bon Iver',
      image: 'https://i.scdn.co/image/d5ea2b221938b03e2096ef2c2caf2a0558014c1e',
      link: 'https://open.spotify.com/artist/4LEiUm1SRbFMgfqnQTwUbQ',
      genres: ['eau claire indie', 'melancholia', 'slowcore'],
    },
    {
      name: 'Mac DeMarco',
      image: 'https://i.scdn.co/image/e3d3e28c604a1c86e796e0d2aa7d4dc249f62e6f',
      link: 'https://open.spotify.com/artist/3Sz7ZnJQBIHsXLUSo0OQtM',
      genres: ['edmonton indie'],
    },
    {
      name: 'Bombay Bicycle Club',
      image: 'https://i.scdn.co/image/4a1e106fead0523ef38b09ebc5f83688e7bf7129',
      link: 'https://open.spotify.com/artist/3pTE9iaJTkWns3mxpNQlJV',
      genres: [
        'alternative dance',
        'british indie rock',
        'indie pop',
        'indie rock',
        'indietronica',
        'modern alternative rock',
        'modern rock',
        'new rave',
        'rock',
      ],
    },
    {
      name: 'Pompeya',
      image: 'https://i.scdn.co/image/36579841d646bd87bf12eee2c9da60430a2e1097',
      link: 'https://open.spotify.com/artist/6ECT62UWPniLG7KmWdwk37',
      genres: ['russian synthpop'],
    },

    {
      name: 'Bon Iver',
      image: 'https://i.scdn.co/image/d5ea2b221938b03e2096ef2c2caf2a0558014c1e',
      link: 'https://open.spotify.com/artist/4LEiUm1SRbFMgfqnQTwUbQ',
      genres: ['eau claire indie', 'melancholia', 'slowcore'],
    },
    {
      name: 'Mac DeMarco',
      image: 'https://i.scdn.co/image/e3d3e28c604a1c86e796e0d2aa7d4dc249f62e6f',
      link: 'https://open.spotify.com/artist/3Sz7ZnJQBIHsXLUSo0OQtM',
      genres: ['edmonton indie'],
    },
    {
      name: 'Bombay Bicycle Club',
      image: 'https://i.scdn.co/image/4a1e106fead0523ef38b09ebc5f83688e7bf7129',
      link: 'https://open.spotify.com/artist/3pTE9iaJTkWns3mxpNQlJV',
      genres: [
        'alternative dance',
        'british indie rock',
        'indie pop',
        'indie rock',
        'indietronica',
        'modern alternative rock',
        'modern rock',
        'new rave',
        'rock',
      ],
    },
    {
      name: 'Pompeya',
      image: 'https://i.scdn.co/image/36579841d646bd87bf12eee2c9da60430a2e1097',
      link: 'https://open.spotify.com/artist/6ECT62UWPniLG7KmWdwk37',
      genres: ['russian synthpop'],
    },
    {
      name: 'Bon Iver',
      image: 'https://i.scdn.co/image/d5ea2b221938b03e2096ef2c2caf2a0558014c1e',
      link: 'https://open.spotify.com/artist/4LEiUm1SRbFMgfqnQTwUbQ',
      genres: ['eau claire indie', 'melancholia', 'slowcore'],
    },
    {
      name: 'Mac DeMarco',
      image: 'https://i.scdn.co/image/e3d3e28c604a1c86e796e0d2aa7d4dc249f62e6f',
      link: 'https://open.spotify.com/artist/3Sz7ZnJQBIHsXLUSo0OQtM',
      genres: ['edmonton indie'],
    },
    {
      name: 'Bombay Bicycle Club',
      image: 'https://i.scdn.co/image/4a1e106fead0523ef38b09ebc5f83688e7bf7129',
      link: 'https://open.spotify.com/artist/3pTE9iaJTkWns3mxpNQlJV',
      genres: [
        'alternative dance',
        'british indie rock',
        'indie pop',
        'indie rock',
        'indietronica',
        'modern alternative rock',
        'modern rock',
        'new rave',
        'rock',
      ],
    },
    {
      name: 'Pompeya',
      image: 'https://i.scdn.co/image/36579841d646bd87bf12eee2c9da60430a2e1097',
      link: 'https://open.spotify.com/artist/6ECT62UWPniLG7KmWdwk37',
      genres: ['russian synthpop'],
    },
  ],

  tracks: {
    href:
      'https://api.spotify.com/v1/search?query=Hi&type=track&offset=0&limit=10',
    items: [
      {
        album: {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/0Y5tJX1MQlPlqiwlOH1tJY',
              },
              href: 'https://api.spotify.com/v1/artists/0Y5tJX1MQlPlqiwlOH1tJY',
              id: '0Y5tJX1MQlPlqiwlOH1tJY',
              name: 'Travis Scott',
              type: 'artist',
              uri: 'spotify:artist:0Y5tJX1MQlPlqiwlOH1tJY',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/2uDTi1PlpSpvAv7IRAoAEU',
          },
          href: 'https://api.spotify.com/v1/albums/2uDTi1PlpSpvAv7IRAoAEU',
          id: '2uDTi1PlpSpvAv7IRAoAEU',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273e42b5fea4ac4c3d6328b622b',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02e42b5fea4ac4c3d6328b622b',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851e42b5fea4ac4c3d6328b622b',
              width: 64,
            },
          ],
          name: 'HIGHEST IN THE ROOM',
          release_date: '2019-10-04',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:2uDTi1PlpSpvAv7IRAoAEU',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0Y5tJX1MQlPlqiwlOH1tJY',
            },
            href: 'https://api.spotify.com/v1/artists/0Y5tJX1MQlPlqiwlOH1tJY',
            id: '0Y5tJX1MQlPlqiwlOH1tJY',
            name: 'Travis Scott',
            type: 'artist',
            uri: 'spotify:artist:0Y5tJX1MQlPlqiwlOH1tJY',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AL',
          'AR',
          'AT',
          'AU',
          'BA',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'BY',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HR',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'KZ',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MK',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'SA',
          'SE',
          'SG',
          'SI',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UA',
          'US',
          'UY',
          'VN',
          'XK',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 175720,
        explicit: true,
        external_ids: {
          isrc: 'USSM11904276',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/3eekarcy7kvN4yt5ZFzltW',
        },
        href: 'https://api.spotify.com/v1/tracks/3eekarcy7kvN4yt5ZFzltW',
        id: '3eekarcy7kvN4yt5ZFzltW',
        is_local: false,
        name: 'HIGHEST IN THE ROOM',
        popularity: 90,
        preview_url:
          'https://p.scdn.co/mp3-preview/d9b90990dab9d8376d05c5d4a6b7ac3e99c03763?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:3eekarcy7kvN4yt5ZFzltW',
      },
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/0XATRDCYuuGhk0oE7C0o5G',
              },
              href: 'https://api.spotify.com/v1/artists/0XATRDCYuuGhk0oE7C0o5G',
              id: '0XATRDCYuuGhk0oE7C0o5G',
              name: 'MAMAMOO',
              type: 'artist',
              uri: 'spotify:artist:0XATRDCYuuGhk0oE7C0o5G',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/7CucpzwxAZ6kHmctI9eo4X',
          },
          href: 'https://api.spotify.com/v1/albums/7CucpzwxAZ6kHmctI9eo4X',
          id: '7CucpzwxAZ6kHmctI9eo4X',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b2739d650d0d98caf3f54b842a0b',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e029d650d0d98caf3f54b842a0b',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d000048519d650d0d98caf3f54b842a0b',
              width: 64,
            },
          ],
          name: 'reality in BLACK',
          release_date: '2019-11-14',
          release_date_precision: 'day',
          total_tracks: 11,
          type: 'album',
          uri: 'spotify:album:7CucpzwxAZ6kHmctI9eo4X',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0XATRDCYuuGhk0oE7C0o5G',
            },
            href: 'https://api.spotify.com/v1/artists/0XATRDCYuuGhk0oE7C0o5G',
            id: '0XATRDCYuuGhk0oE7C0o5G',
            name: 'MAMAMOO',
            type: 'artist',
            uri: 'spotify:artist:0XATRDCYuuGhk0oE7C0o5G',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AL',
          'AR',
          'AT',
          'AU',
          'BA',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'BY',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HR',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'KW',
          'KZ',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MK',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'SA',
          'SE',
          'SG',
          'SI',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UA',
          'US',
          'UY',
          'VN',
          'XK',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 195306,
        explicit: false,
        external_ids: {
          isrc: 'KRA381904798',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/24nK8tW7Pt3Inh2utttuoG',
        },
        href: 'https://api.spotify.com/v1/tracks/24nK8tW7Pt3Inh2utttuoG',
        id: '24nK8tW7Pt3Inh2utttuoG',
        is_local: false,
        name: 'HIP',
        popularity: 76,
        preview_url:
          'https://p.scdn.co/mp3-preview/f676e3fb643977d83d2e2a88b487e2ea9431e19a?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 4,
        type: 'track',
        uri: 'spotify:track:24nK8tW7Pt3Inh2utttuoG',
      },
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/20JZFwl6HVl6yg8a4H3ZqK',
              },
              href: 'https://api.spotify.com/v1/artists/20JZFwl6HVl6yg8a4H3ZqK',
              id: '20JZFwl6HVl6yg8a4H3ZqK',
              name: 'Panic! At The Disco',
              type: 'artist',
              uri: 'spotify:artist:20JZFwl6HVl6yg8a4H3ZqK',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/6ApYSpXF8GxZAgBTHDzYge',
          },
          href: 'https://api.spotify.com/v1/albums/6ApYSpXF8GxZAgBTHDzYge',
          id: '6ApYSpXF8GxZAgBTHDzYge',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273c5148520a59be191eea16989',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02c5148520a59be191eea16989',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851c5148520a59be191eea16989',
              width: 64,
            },
          ],
          name: 'Pray for the Wicked',
          release_date: '2018-06-22',
          release_date_precision: 'day',
          total_tracks: 11,
          type: 'album',
          uri: 'spotify:album:6ApYSpXF8GxZAgBTHDzYge',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/20JZFwl6HVl6yg8a4H3ZqK',
            },
            href: 'https://api.spotify.com/v1/artists/20JZFwl6HVl6yg8a4H3ZqK',
            id: '20JZFwl6HVl6yg8a4H3ZqK',
            name: 'Panic! At The Disco',
            type: 'artist',
            uri: 'spotify:artist:20JZFwl6HVl6yg8a4H3ZqK',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AL',
          'AR',
          'AT',
          'AU',
          'BA',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'BY',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HR',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'KZ',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MK',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'SA',
          'SE',
          'SG',
          'SI',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UA',
          'US',
          'UY',
          'VN',
          'XK',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 190946,
        explicit: false,
        external_ids: {
          isrc: 'USAT21801174',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/1rqqCSm0Qe4I9rUvWncaom',
        },
        href: 'https://api.spotify.com/v1/tracks/1rqqCSm0Qe4I9rUvWncaom',
        id: '1rqqCSm0Qe4I9rUvWncaom',
        is_local: false,
        name: 'High Hopes',
        popularity: 85,
        preview_url:
          'https://p.scdn.co/mp3-preview/f6404b1b3199442271c17d9e1461c3f2a52018f8?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 4,
        type: 'track',
        uri: 'spotify:track:1rqqCSm0Qe4I9rUvWncaom',
      },
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/711MCceyCBcFnzjGY4Q7Un',
              },
              href: 'https://api.spotify.com/v1/artists/711MCceyCBcFnzjGY4Q7Un',
              id: '711MCceyCBcFnzjGY4Q7Un',
              name: 'AC/DC',
              type: 'artist',
              uri: 'spotify:artist:711MCceyCBcFnzjGY4Q7Un',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/10v912xgTZbjAtYfyKWJCS',
          },
          href: 'https://api.spotify.com/v1/albums/10v912xgTZbjAtYfyKWJCS',
          id: '10v912xgTZbjAtYfyKWJCS',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b27351c02a77d09dfcd53c8676d0',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e0251c02a77d09dfcd53c8676d0',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d0000485151c02a77d09dfcd53c8676d0',
              width: 64,
            },
          ],
          name: 'Highway to Hell',
          release_date: '1979-07-27',
          release_date_precision: 'day',
          total_tracks: 10,
          type: 'album',
          uri: 'spotify:album:10v912xgTZbjAtYfyKWJCS',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/711MCceyCBcFnzjGY4Q7Un',
            },
            href: 'https://api.spotify.com/v1/artists/711MCceyCBcFnzjGY4Q7Un',
            id: '711MCceyCBcFnzjGY4Q7Un',
            name: 'AC/DC',
            type: 'artist',
            uri: 'spotify:artist:711MCceyCBcFnzjGY4Q7Un',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AL',
          'AR',
          'AT',
          'AU',
          'BA',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'BY',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HR',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'KZ',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MK',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'SA',
          'SE',
          'SG',
          'SI',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UA',
          'US',
          'UY',
          'VN',
          'XK',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 208400,
        explicit: false,
        external_ids: {
          isrc: 'AUAP07900028',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/2zYzyRzz6pRmhPzyfMEC8s',
        },
        href: 'https://api.spotify.com/v1/tracks/2zYzyRzz6pRmhPzyfMEC8s',
        id: '2zYzyRzz6pRmhPzyfMEC8s',
        is_local: false,
        name: 'Highway to Hell',
        popularity: 84,
        preview_url:
          'https://p.scdn.co/mp3-preview/db138a9742397601a1e5fdde727967956bdad0fb?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:2zYzyRzz6pRmhPzyfMEC8s',
      },
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/02kJSzxNuaWGqwubyUba0Z',
              },
              href: 'https://api.spotify.com/v1/artists/02kJSzxNuaWGqwubyUba0Z',
              id: '02kJSzxNuaWGqwubyUba0Z',
              name: 'G-Eazy',
              type: 'artist',
              uri: 'spotify:artist:02kJSzxNuaWGqwubyUba0Z',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/1VAc77UvK5wj8ZSWCo3V2b',
          },
          href: 'https://api.spotify.com/v1/albums/1VAc77UvK5wj8ZSWCo3V2b',
          id: '1VAc77UvK5wj8ZSWCo3V2b',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273046527a9c176f7c2916f3530',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02046527a9c176f7c2916f3530',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851046527a9c176f7c2916f3530',
              width: 64,
            },
          ],
          name: 'The Beautiful & Damned',
          release_date: '2017-12-15',
          release_date_precision: 'day',
          total_tracks: 20,
          type: 'album',
          uri: 'spotify:album:1VAc77UvK5wj8ZSWCo3V2b',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/02kJSzxNuaWGqwubyUba0Z',
            },
            href: 'https://api.spotify.com/v1/artists/02kJSzxNuaWGqwubyUba0Z',
            id: '02kJSzxNuaWGqwubyUba0Z',
            name: 'G-Eazy',
            type: 'artist',
            uri: 'spotify:artist:02kJSzxNuaWGqwubyUba0Z',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/26VFTg2z8YR0cCuwLzESi2',
            },
            href: 'https://api.spotify.com/v1/artists/26VFTg2z8YR0cCuwLzESi2',
            id: '26VFTg2z8YR0cCuwLzESi2',
            name: 'Halsey',
            type: 'artist',
            uri: 'spotify:artist:26VFTg2z8YR0cCuwLzESi2',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AL',
          'AR',
          'AT',
          'AU',
          'BA',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'BY',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HR',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'KZ',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MK',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'SA',
          'SE',
          'SG',
          'SI',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UA',
          'US',
          'UY',
          'VN',
          'XK',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 268866,
        explicit: true,
        external_ids: {
          isrc: 'USRC11701867',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/5k38wzpLb15YgncyWdTZE4',
        },
        href: 'https://api.spotify.com/v1/tracks/5k38wzpLb15YgncyWdTZE4',
        id: '5k38wzpLb15YgncyWdTZE4',
        is_local: false,
        name: 'Him & I (with Halsey)',
        popularity: 76,
        preview_url:
          'https://p.scdn.co/mp3-preview/ed7a2ff3c91a5a1b48a6b270debe123e076ac82d?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 3,
        type: 'track',
        uri: 'spotify:track:5k38wzpLb15YgncyWdTZE4',
      },
      {
        album: {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/1MXZ0hsGic96dWRDKwAwdr',
              },
              href: 'https://api.spotify.com/v1/artists/1MXZ0hsGic96dWRDKwAwdr',
              id: '1MXZ0hsGic96dWRDKwAwdr',
              name: 'Tyla Yaweh',
              type: 'artist',
              uri: 'spotify:artist:1MXZ0hsGic96dWRDKwAwdr',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/0imwCieoxougGmptrN1WAx',
          },
          href: 'https://api.spotify.com/v1/albums/0imwCieoxougGmptrN1WAx',
          id: '0imwCieoxougGmptrN1WAx',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b2732dea10a6e67a8c1ab8b8566e',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e022dea10a6e67a8c1ab8b8566e',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d000048512dea10a6e67a8c1ab8b8566e',
              width: 64,
            },
          ],
          name: 'High Right Now (feat. Wiz Khalifa) [Remix]',
          release_date: '2020-01-31',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:0imwCieoxougGmptrN1WAx',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1MXZ0hsGic96dWRDKwAwdr',
            },
            href: 'https://api.spotify.com/v1/artists/1MXZ0hsGic96dWRDKwAwdr',
            id: '1MXZ0hsGic96dWRDKwAwdr',
            name: 'Tyla Yaweh',
            type: 'artist',
            uri: 'spotify:artist:1MXZ0hsGic96dWRDKwAwdr',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop',
            },
            href: 'https://api.spotify.com/v1/artists/137W8MRPWKqSmrBGDBFSop',
            id: '137W8MRPWKqSmrBGDBFSop',
            name: 'Wiz Khalifa',
            type: 'artist',
            uri: 'spotify:artist:137W8MRPWKqSmrBGDBFSop',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AL',
          'AR',
          'AT',
          'AU',
          'BA',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'BY',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HR',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'KZ',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MK',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'SA',
          'SE',
          'SG',
          'SI',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UA',
          'US',
          'UY',
          'VN',
          'XK',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 175759,
        explicit: true,
        external_ids: {
          isrc: 'USSM12000392',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/5DPASDOoVakOcD8EIhb46T',
        },
        href: 'https://api.spotify.com/v1/tracks/5DPASDOoVakOcD8EIhb46T',
        id: '5DPASDOoVakOcD8EIhb46T',
        is_local: false,
        name: 'High Right Now (feat. Wiz Khalifa) - Remix',
        popularity: 76,
        preview_url:
          'https://p.scdn.co/mp3-preview/468c8f7f258f03b1d49e983da88abda51e327b69?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:5DPASDOoVakOcD8EIhb46T',
      },
      {
        album: {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/23fqKkggKUBHNkbKtXEls4',
              },
              href: 'https://api.spotify.com/v1/artists/23fqKkggKUBHNkbKtXEls4',
              id: '23fqKkggKUBHNkbKtXEls4',
              name: 'Kygo',
              type: 'artist',
              uri: 'spotify:artist:23fqKkggKUBHNkbKtXEls4',
            },
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/6XpaIBNiVzIetEPCWDvAFP',
              },
              href: 'https://api.spotify.com/v1/artists/6XpaIBNiVzIetEPCWDvAFP',
              id: '6XpaIBNiVzIetEPCWDvAFP',
              name: 'Whitney Houston',
              type: 'artist',
              uri: 'spotify:artist:6XpaIBNiVzIetEPCWDvAFP',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/4wquJImu8RtyEuDtIAsfcE',
          },
          href: 'https://api.spotify.com/v1/albums/4wquJImu8RtyEuDtIAsfcE',
          id: '4wquJImu8RtyEuDtIAsfcE',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b2737c8977a0ad3a3a0627be9ed7',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e027c8977a0ad3a3a0627be9ed7',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d000048517c8977a0ad3a3a0627be9ed7',
              width: 64,
            },
          ],
          name: 'Higher Love',
          release_date: '2019-06-28',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:4wquJImu8RtyEuDtIAsfcE',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/23fqKkggKUBHNkbKtXEls4',
            },
            href: 'https://api.spotify.com/v1/artists/23fqKkggKUBHNkbKtXEls4',
            id: '23fqKkggKUBHNkbKtXEls4',
            name: 'Kygo',
            type: 'artist',
            uri: 'spotify:artist:23fqKkggKUBHNkbKtXEls4',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/6XpaIBNiVzIetEPCWDvAFP',
            },
            href: 'https://api.spotify.com/v1/artists/6XpaIBNiVzIetEPCWDvAFP',
            id: '6XpaIBNiVzIetEPCWDvAFP',
            name: 'Whitney Houston',
            type: 'artist',
            uri: 'spotify:artist:6XpaIBNiVzIetEPCWDvAFP',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AL',
          'AR',
          'AT',
          'AU',
          'BA',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'BY',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HR',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'KZ',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MK',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'SA',
          'SE',
          'SG',
          'SI',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UA',
          'US',
          'UY',
          'VN',
          'XK',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 228267,
        explicit: false,
        external_ids: {
          isrc: 'USRC11901901',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/6oJ6le65B3SEqPwMRNXWjY',
        },
        href: 'https://api.spotify.com/v1/tracks/6oJ6le65B3SEqPwMRNXWjY',
        id: '6oJ6le65B3SEqPwMRNXWjY',
        is_local: false,
        name: 'Higher Love',
        popularity: 84,
        preview_url:
          'https://p.scdn.co/mp3-preview/a74efdaa12f708673a14fdf67bfb6ec365d8ebf0?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:6oJ6le65B3SEqPwMRNXWjY',
      },
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/7DuTB6wdzqFJGFLSH17k8e',
              },
              href: 'https://api.spotify.com/v1/artists/7DuTB6wdzqFJGFLSH17k8e',
              id: '7DuTB6wdzqFJGFLSH17k8e',
              name: 'Bhad Bhabie',
              type: 'artist',
              uri: 'spotify:artist:7DuTB6wdzqFJGFLSH17k8e',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/5I0eRWD0PLOmswFHZhcD12',
          },
          href: 'https://api.spotify.com/v1/albums/5I0eRWD0PLOmswFHZhcD12',
          id: '5I0eRWD0PLOmswFHZhcD12',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b2734230e47d7122807dc73e8bc7',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e024230e47d7122807dc73e8bc7',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d000048514230e47d7122807dc73e8bc7',
              width: 64,
            },
          ],
          name: '15',
          release_date: '2018-09-18',
          release_date_precision: 'day',
          total_tracks: 15,
          type: 'album',
          uri: 'spotify:album:5I0eRWD0PLOmswFHZhcD12',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7DuTB6wdzqFJGFLSH17k8e',
            },
            href: 'https://api.spotify.com/v1/artists/7DuTB6wdzqFJGFLSH17k8e',
            id: '7DuTB6wdzqFJGFLSH17k8e',
            name: 'Bhad Bhabie',
            type: 'artist',
            uri: 'spotify:artist:7DuTB6wdzqFJGFLSH17k8e',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AL',
          'AR',
          'AT',
          'AU',
          'BA',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'BY',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HR',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'KZ',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MK',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'SA',
          'SE',
          'SG',
          'SI',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UA',
          'US',
          'UY',
          'VN',
          'XK',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 105130,
        explicit: true,
        external_ids: {
          isrc: 'USAT21703862',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/3yjpv3Rk2gkHhfhgBjiUKS',
        },
        href: 'https://api.spotify.com/v1/tracks/3yjpv3Rk2gkHhfhgBjiUKS',
        id: '3yjpv3Rk2gkHhfhgBjiUKS',
        is_local: false,
        name: 'Hi Bich',
        popularity: 65,
        preview_url:
          'https://p.scdn.co/mp3-preview/cf18cdf539f5e03685f04845a6896bb488b3fb71?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 11,
        type: 'track',
        uri: 'spotify:track:3yjpv3Rk2gkHhfhgBjiUKS',
      },
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/757aE44tKEUQEqRuT6GnEB',
              },
              href: 'https://api.spotify.com/v1/artists/757aE44tKEUQEqRuT6GnEB',
              id: '757aE44tKEUQEqRuT6GnEB',
              name: 'Roddy Ricch',
              type: 'artist',
              uri: 'spotify:artist:757aE44tKEUQEqRuT6GnEB',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/52u4anZbHd6UInnmHRFzba',
          },
          href: 'https://api.spotify.com/v1/albums/52u4anZbHd6UInnmHRFzba',
          id: '52u4anZbHd6UInnmHRFzba',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b273600adbc750285ea1a8da249f',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e02600adbc750285ea1a8da249f',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d00004851600adbc750285ea1a8da249f',
              width: 64,
            },
          ],
          name: 'Please Excuse Me For Being Antisocial',
          release_date: '2019-12-06',
          release_date_precision: 'day',
          total_tracks: 16,
          type: 'album',
          uri: 'spotify:album:52u4anZbHd6UInnmHRFzba',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/757aE44tKEUQEqRuT6GnEB',
            },
            href: 'https://api.spotify.com/v1/artists/757aE44tKEUQEqRuT6GnEB',
            id: '757aE44tKEUQEqRuT6GnEB',
            name: 'Roddy Ricch',
            type: 'artist',
            uri: 'spotify:artist:757aE44tKEUQEqRuT6GnEB',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0YinUQ50QDB7ZxSCLyQ40k',
            },
            href: 'https://api.spotify.com/v1/artists/0YinUQ50QDB7ZxSCLyQ40k',
            id: '0YinUQ50QDB7ZxSCLyQ40k',
            name: 'Mustard',
            type: 'artist',
            uri: 'spotify:artist:0YinUQ50QDB7ZxSCLyQ40k',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AL',
          'AR',
          'AT',
          'AU',
          'BA',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'BY',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HR',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'KZ',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MK',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'SA',
          'SE',
          'SG',
          'SI',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UA',
          'US',
          'UY',
          'VN',
          'XK',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 220486,
        explicit: true,
        external_ids: {
          isrc: 'USAT21906985',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/07KXEDMj78x68D884wgVEm',
        },
        href: 'https://api.spotify.com/v1/tracks/07KXEDMj78x68D884wgVEm',
        id: '07KXEDMj78x68D884wgVEm',
        is_local: false,
        name: 'High Fashion (feat. Mustard)',
        popularity: 85,
        preview_url:
          'https://p.scdn.co/mp3-preview/f1897162d24233245eeafa90af45ce969845b29b?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 11,
        type: 'track',
        uri: 'spotify:track:07KXEDMj78x68D884wgVEm',
      },
      {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp',
              },
              href: 'https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp',
              id: '0EmeFodog0BfCgMzAIvKQp',
              name: 'Shakira',
              type: 'artist',
              uri: 'spotify:artist:0EmeFodog0BfCgMzAIvKQp',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AL',
            'AR',
            'AT',
            'AU',
            'BA',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'BY',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'KZ',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MK',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'SA',
            'SE',
            'SG',
            'SI',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'UA',
            'US',
            'UY',
            'VN',
            'XK',
            'ZA',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/5ppnlEoj4HdRRdRihnY3jU',
          },
          href: 'https://api.spotify.com/v1/albums/5ppnlEoj4HdRRdRihnY3jU',
          id: '5ppnlEoj4HdRRdRihnY3jU',
          images: [
            {
              height: 640,
              url:
                'https://i.scdn.co/image/ab67616d0000b27327ddd747545c0d0cfe7595fa',
              width: 640,
            },
            {
              height: 300,
              url:
                'https://i.scdn.co/image/ab67616d00001e0227ddd747545c0d0cfe7595fa',
              width: 300,
            },
            {
              height: 64,
              url:
                'https://i.scdn.co/image/ab67616d0000485127ddd747545c0d0cfe7595fa',
              width: 64,
            },
          ],
          name: 'Oral Fixation, Vol. 2 (Expanded Edition)',
          release_date: '2005-11-28',
          release_date_precision: 'day',
          total_tracks: 13,
          type: 'album',
          uri: 'spotify:album:5ppnlEoj4HdRRdRihnY3jU',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp',
            },
            href: 'https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp',
            id: '0EmeFodog0BfCgMzAIvKQp',
            name: 'Shakira',
            type: 'artist',
            uri: 'spotify:artist:0EmeFodog0BfCgMzAIvKQp',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7aBzpmFXB4WWpPl2F7RjBe',
            },
            href: 'https://api.spotify.com/v1/artists/7aBzpmFXB4WWpPl2F7RjBe',
            id: '7aBzpmFXB4WWpPl2F7RjBe',
            name: 'Wyclef Jean',
            type: 'artist',
            uri: 'spotify:artist:7aBzpmFXB4WWpPl2F7RjBe',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AL',
          'AR',
          'AT',
          'AU',
          'BA',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'BY',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HR',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'KZ',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MK',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'SA',
          'SE',
          'SG',
          'SI',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'UA',
          'US',
          'UY',
          'VN',
          'XK',
          'ZA',
        ],
        disc_number: 1,
        duration_ms: 218093,
        explicit: false,
        external_ids: {
          isrc: 'USSM10600677',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/3ZFTkvIE7kyPt6Nu3PEa7V',
        },
        href: 'https://api.spotify.com/v1/tracks/3ZFTkvIE7kyPt6Nu3PEa7V',
        id: '3ZFTkvIE7kyPt6Nu3PEa7V',
        is_local: false,
        name: "Hips Don't Lie (feat. Wyclef Jean)",
        popularity: 83,
        preview_url:
          'https://p.scdn.co/mp3-preview/3859547944f57cfb7b996f6551148c9467889d4b?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 3,
        type: 'track',
        uri: 'spotify:track:3ZFTkvIE7kyPt6Nu3PEa7V',
      },
    ],
    limit: 10,
    next:
      'https://api.spotify.com/v1/search?query=Hi&type=track&offset=10&limit=10',
    offset: 0,
    previous: null,
    total: 100010,
  },
};
